server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username: postgres
    password: camal123
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1057135930964-vd4pk6q14s4a8gk4nprrb81rg0q221j5.apps.googleusercontent.com
            client-secret: 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
#            scope: openid, profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
#            user-name-attribute: sub


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: spring-boot-learning
  mail:
    host: smtp.gmail.com
    port: 587
    username: camallaoyrenin@gmail.com
    password: xflw qqma mnqg mmsa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
